### ISSUE TITLE
Add additional styling options for components

### ISSUE THREAD

**Issue by paulreyesdigital** [francis150/geocentric#1]

**Comment by paulreyesdigital** [comment]
- [ ] Section Margins
- [ ] Section Paddings
- [ ] Component Font Styles

**Comment by francis150** [comment]
### General
- [ ] Component Gap
- [ ] Component Padding
- [ ] Font Family

### Weather Component
- [ ] Background Color
- [ ] Text Color
- [ ] Unit

### About Component
- [ ] Title
  - [ ] Font Size
  - [ ] Font Weight
  - [ ] Font Color
  - [ ] Text Alignment
- [ ] Content
  - [ ] Font Size
  - [ ] Font Weight
  - [ ] Font Color
  - [ ] Text Alignment

### Neighborhoods Component
- [ ] Title
  - [ ] Font Size
  - [ ] Font Weight
  - [ ] Font Color
  - [ ] Text Alignment
- [ ] Neighborhoods
  - [ ] Font Size
  - [ ] Font Weight
  - [ ] Font Color
  - [ ] Text Alignment
- [ ] Neighborhoods [Hovered]
  - [ ] Font Size
  - [ ] Font Weight
  - [ ] Font Color
  - [ ] Text Alignment

### Things to Do Component
- [ ] Title
  - [ ] Font Size
  - [ ] Font Weight
  - [ ] Font Color
  - [ ] Text Alignment
- [ ] Items
  - [ ] Background Color
  - [ ] Border Color
  - [ ] Border Radius
  - [ ] Border Width
  - [ ] Gap
  - [ ] Padding
  - [ ] Hover Effect
- [ ] Image
  - [ ] Border Color
  - [ ] Border Radius
  - [ ] Border Width
 - [ ] Name
  - [ ] Font Size
  - [ ] Font Weight
  - [ ] Font Color
  - [ ] Text Alignment
- [ ] Show Ratings

### Bus Stops Component
- [ ] Title
  - [ ] Font Size
  - [ ] Font Weight
  - [ ] Font Color
  - [ ] Text Alignment
- [ ] Items
  - [ ] Background Color
  - [ ] Border Color
  - [ ] Border Radius
  - [ ] Border Width
  - [ ] Gap
  - [ ] Padding
  - [ ] Hover Effect
- [ ] Name
  - [ ] Font Size
  - [ ] Font Weight
  - [ ] Font Color
  - [ ] Text Alignment

### Map Embed Component
- [ ] Title
  - [ ] Font Size
  - [ ] Font Weight
  - [ ] Font Color
  - [ ] Text Alignment
- [ ] Map
  - [ ] Height (px)
  - [ ] Width (%)

### Driving Directions Component
- [ ] Title
  - [ ] Font Size
  - [ ] Font Weight
  - [ ] Font Color
  - [ ] Text Alignment
- [ ] Map
  - [ ] Height (px)
  - [ ] Width (%)

### Reviews Component
- [ ] Title
  - [ ] Font Size
  - [ ] Font Weight
  - [ ] Font Color
  - [ ] Text Alignment
- [ ] Items
  - [ ] Background Color
  - [ ] Border Color
  - [ ] Border Radius
  - [ ] Border Width
  - [ ] Gap
  - [ ] Padding
  - [ ] Hover Effect
- [ ] Author Name
  - [ ] Font Size
  - [ ] Font Weight
  - [ ] Font Color
- [ ] Review Body
  - [ ] Font Size
  - [ ] Font Weight
  - [ ] Font Color
